### ISSUE TITLE
UDIR ytelsetest

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#586]
## Description
Analyse the logs produced after the testing activities by UDIR.
Test sessions:
- 18/10 10:00-11:00
- 19/10 10:00-12:00

Perform new tests in the performance test environment.

## Threat modeling
This issue does not introduce changes directly.

**Comment by HenningNormann** [comment]
With high volumes udir got some errors in their performance tests. These errors were different kind of sockets exceptions. It was hard to find the root cause of this problem.

We have done our own tests to analyze in more detail. These tests use a copy of the udir app deployed to yt01 and a local machine. We have not been able to reproduce the socket exceptions. The first bottleneck in the tests was Cosmos DB Cpu (RU). After increasing RU from 20k to 40k in yt01 the bottleneck was moved to lack of cpu for the storage platform component.

Some local tests were run to compare the current Cosmos configuration to the upcoming Postgres configuration - to see the potential of the new configuration. These tests were run with the app and storage and authorization platform components locally. All other resources (including Cosmos/Postegres) were in yt01. The table below shows that the cpu consumption in the storage component is lower with Postgres, and the throughput and response times are better.

![image](https://github.com/Altinn/altinn-platform/assets/28589510/bac4c401-a1dc-4161-b820-9d2ccfedd43d)
