### ISSUE TITLE
productioncdn do not auto renew cert

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#923]
### Description of the bug

productioncdn is supposed to renew cert automatic. This is not working as expected.
service stop at "Pending revalidation" - this should be fixed.

### Steps To Reproduce

1. Check productioncdn resource.

**Comment by tjololo** [comment]
I have checked the _dnsauth txt record and it seems to be up-to-date, and I see that the alternative subdomain we have setup is renewing as expected. Should we create an issue with azure as I cant see any difference in portal leading to why the renewal isn't working. The setup is a bit different since one is a apex-domain and other is a subdomain. Subdomains are easier as they can use CNAME, but thats not an option for the apex-domain.

**Comment by bengtfredh** [comment]
@tjololo We should probably create an issue with support. I wanted to check this, because last month it stopped working when cert expired. At that time _dnsauth was correct, but it renewed the cert when I created a new secret and updated.

**Comment by bengtfredh** [comment]
@tjololo I was starting to create a support request. They redirected me to the doc.
https://learn.microsoft.com/en-us/azure/frontdoor/apex-domain?WT.mc_id=Portal-Microsoft_Azure_AFDX#azure-front-door-managed-tls-certificate-rotation
I guess for apex domains we need to update the secret for every renewal.

**Comment by bengtfredh** [comment]
I have started validation now - give us time to figure out how to automate it.

**Comment by bengtfredh** [comment]
Deployed: 181 day(s) to expiry (from today 10/9/2024)

**Comment by bengtfredh** [comment]
Close this for now - I think automation of tls cert is a bigger issues we will address later. The manual step here is smaller then for other certs.
